{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "aegis.fullname" . }}-api
  labels:
    {{- include "aegis.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "aegis.api.selectorLabels" . | nindent 6 }}
{{- if .Values.worker.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "aegis.fullname" . }}-worker
  labels:
    {{- include "aegis.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "aegis.worker.selectorLabels" . | nindent 6 }}
{{- end }}
{{- end }}
