{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aegis.fullname" . }}-secrets
  labels:
    {{- include "aegis.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.data }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
